USE WebStoreDB;

INSERT INTO ShoppingCarts (UserId, Name, Description) VALUES

(5, 'favorite', 'Your favorite products'),
(5, 'shopping-busket', 'Your shopping cart'),
(6, 'favorite', 'Your favorite products'),
(6, 'shopping-busket', 'Your shopping cart'),
(7, 'favorite', 'Your favorite products'),
(7, 'shopping-busket', 'Your shopping cart'),
(8, 'favorite', 'Your favorite products'),
(8, 'shopping-busket', 'Your shopping cart'),
(9, 'favorite', 'Your favorite products'),
(9, 'shopping-busket', 'Your shopping cart'),
(10, 'favorite', 'Your favorite products'),
(10, 'shopping-busket', 'Your shopping cart'),
(11, 'favorite', 'Your favorite products'),
(11, 'shopping-busket', 'Your shopping cart'),
(12, 'favorite', 'Your favorite products'),
(12, 'shopping-busket', 'Your shopping cart'),
(13, 'favorite', 'Your favorite products'),
(13, 'shopping-busket', 'Your shopping cart'),
(14, 'favorite', 'Your favorite products'),
(14, 'shopping-busket', 'Your shopping cart'),
(15, 'favorite', 'Your favorite products'),
(15, 'shopping-busket', 'Your shopping cart'),
(16, 'favorite', 'Your favorite products'),
(16, 'shopping-busket', 'Your shopping cart'),
(17, 'favorite', 'Your favorite products'),
(17, 'shopping-busket', 'Your shopping cart'),
(18, 'favorite', 'Your favorite products'),
(18, 'shopping-busket', 'Your shopping cart'),
(19, 'favorite', 'Your favorite products'),
(19, 'shopping-busket', 'Your shopping cart');